# Generated by Django 2.0.4 on 2020-01-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_commodity'),
        ('gcmf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityInCorridor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gcmf_commodity', models.BooleanField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Commodity')),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcmf.Corridor')),
            ],
        ),
    ]
