# Generated by Django 2.0.4 on 2020-01-30 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_commodity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implementation_reqs_mt', models.FloatField()),
                ('implementation_shortfalls_mt', models.FloatField()),
                ('implementation_resourced_mt', models.FloatField()),
                ('implementation_reqs_fcr', models.FloatField()),
                ('implementation_shortfalls_fcr', models.FloatField()),
                ('implementation_resourced_fcr', models.FloatField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Commodity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Country')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Period')),
                ('wbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.WBSElement')),
            ],
        ),
    ]
